openapi: 3.0.3
info:
  title: HTTPBin API
  description: A simple API spec for requests to /httpbin.
  version: "2.0.0"
servers:
  - url: https://example.com
  - url: https://example.org

tags:
  - name: HTTPBin

paths:
  /httpbin:
    get:
      summary: Get HTTPBin data
      description: Retrieves data from the HTTPBin endpoint.
      security:
        - openIdAuth: []
        - basicAuth: []
      tags:
        - HTTPBin
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  url:
                    type: string
                    description: The URL of the request.
                  args:
                    type: object
                    additionalProperties:
                      type: string
                    description: Query parameters sent in the request.
                  headers:
                    type: object
                    additionalProperties:
                      type: string
                    description: Headers sent in the request.
        '400':
          description: Bad request
    post:
      summary: Post data to HTTPBin
      description: Posts data to the HTTPBin endpoint.
      security:
        - openIdAuth: []
        - basicAuth: []
      tags:
        - HTTPBin
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                data:
                  type: string
                  description: The data to post.
        description: The data to post to the endpoint.
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  url:
                    type: string
                    description: The URL of the request.
                  args:
                    type: object
                    additionalProperties:
                      type: string
                    description: Query parameters sent in the request.
                  headers:
                    type: object
                    additionalProperties:
                      type: string
                    description: Headers sent in the request.
                  json:
                    type: object
                    additionalProperties:
                      type: string
                    description: JSON data sent in the request.
        '400':
          description: Bad request
components:
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
    openIdAuth:
      type: openIdConnect
      openIdConnectUrl: https://myidp.com/.well-known/openid-configuration
