openapi: 3.0.3
info:
  title: HTTPBin API
  description: A simple API spec for requests to /httpbin.
  version: "1.0.0"
servers:
  - url: https://example.com

x-konnect-metadata:
  product:
    publish: true
  version:
    deprecate: false
    publish: true
  application_registration:
    enabled: false
    auto_approve: false
  gateway:
    servide_id: null
    control_plane_id: null
  documents:
    sync: true
    dir: examples/docs/httpbin/
  auth_strategy_ids: []

tags:
  - name: HTTPBin

paths:
  /httpbin:
    get:
      summary: Get HTTPBin data
      description: Retrieves data from the HTTPBin endpoint.
      security:
        - openIdAuth: []
        - basicAuth: []
      tags:
        - HTTPBin
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  url:
                    type: string
                    description: The URL of the request.
                  args:
                    type: object
                    additionalProperties:
                      type: string
                    description: Query parameters sent in the request.
                  headers:
                    type: object
                    additionalProperties:
                      type: string
                    description: Headers sent in the request.
        '400':
          description: Bad request
components:
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
    openIdAuth:
      type: openIdConnect
      openIdConnectUrl: https://myidp.com/.well-known/openid-configuration
